#table(
  columns: (1fr, 1fr),
  stroke: none,
  table.hline(stroke: 1pt),
  [Variable], [Definition],
  table.hline(stroke: 0.5pt),
  [name], [Name of the institution],
  [year], [Observation year],
  [inst\_id], [Unique institution identifier],
  [country\_code], [Country code of the institution],
  [type], [Type or category of institution],
  [n\_publication], [Number of publications],
  [ace\_1], [Academic excellence/collaboration indicator 1],
  [ace\_2], [Academic excellence/collaboration indicator 2],
  [deltas\_1], [Change (delta) indicator 1],
  [gdp\_cap], [GDP per capita],
  [gdp\_growth], [Annual GDP growth rate],
  [internet], [Internet penetration rate],
  [electricity], [Access to electricity rate],
  [tertiary\_enrol], [Tertiary education enrollment rate],
  [education\_exp], [Education expenditure (% of GDP)],
  [rd\_exp], [Research and development expenditure (% of GDP)],
  [researchers], [Number of researchers],
  [n\_citations], [Number of citations received],
  table.hline(stroke: 1pt)
)
